name: airtecs_movil
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  shared_preferences: ^2.3.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/AirTecs.png"
  adaptive_icon_foreground: "lib/assets/images/AirTecs.png"  # Imagen principal
  adaptive_icon_background: "#3276E8"  # Color de fondo en Android
  remove_alpha_ios: true  # Evita problemas en iOS
